name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
author: Maxim Vatentsov <admin@gtn-craft.ru>
version: ${project.version}

commands:
   server:
      description: Teleport to another server
      usage: /<command> <server> [player]
      permission: bungeecord.server.use

permissions:
   bungeecord.server.use:
      description: Allow send other player to server.
      default: true
   bungeecord.server.other:
      description: Allow send other player to server.
      default: op
